"""Service port protocols — contracts for API client and telemetry source."""
from __future__ import annotations

from typing import TYPE_CHECKING, Protocol

if TYPE_CHECKING:
    from datetime import datetime
    from pathlib import Path
    from queue import SimpleQueue

    from smart_pid_domain.dtos import (
        CommandResponse,
        ControllerResponse,
        HistoryResponse,
        SimulatorStatusResponse,
        TokenResponse,
    )
    from smart_pid_domain.dtos.users import UserResponse


class TelemetrySourcePort(Protocol):
    """Contract for real-time telemetry data source."""

    def start(self) -> None: ...
    def stop(self) -> None: ...

    @property
    def queue(self) -> SimpleQueue: ...


class APIClientPort(Protocol):
    """Contract for REST API client (sync)."""

    # Auth
    def login(self, username: str, password: str) -> TokenResponse: ...

    # Controllers
    def list_controllers(self) -> list[ControllerResponse]: ...
    def get_controller(self, controller_id: int) -> ControllerResponse: ...
    def update_controller(
        self, controller_id: int, data: dict,
    ) -> ControllerResponse: ...

    # Commands
    def set_setpoint(self, controller_id: int, value: float) -> CommandResponse: ...
    def set_mode(self, controller_id: int, mode: str) -> CommandResponse: ...
    def set_output(self, controller_id: int, value: float) -> CommandResponse: ...

    # History
    def get_history(
        self, controller_id: int, start: datetime, end: datetime,
    ) -> HistoryResponse: ...

    # Simulator
    def get_simulator_status(self) -> SimulatorStatusResponse: ...
    def set_simulator_preset(
        self, controller_id: int, preset: str,
    ) -> CommandResponse: ...
    def set_simulator_parameters(
        self, controller_id: int, gain: float, tau1: float,
        tau2: float | None, dead_time: float,
    ) -> CommandResponse: ...
    def inject_simulator_disturbance(
        self, controller_id: int, dist_type: str, amplitude: float,
    ) -> CommandResponse: ...
    def clear_simulator_disturbance(self, controller_id: int) -> CommandResponse: ...

    # Simulator PID
    def enable_simulator_pid(
        self, controller_id: int, enabled: bool,
    ) -> CommandResponse: ...
    def set_simulator_pid_params(
        self, controller_id: int, kp: float, ti: float, td: float,
    ) -> CommandResponse: ...
    def set_simulator_pid_mode(
        self, controller_id: int, mode: str,
    ) -> CommandResponse: ...
    def get_simulator_pid_status(
        self, controller_id: int,
    ) -> dict: ...

    # Alarms
    def get_active_alarms(self, controller_id: int | None = ...) -> list[dict]: ...
    def ack_alarm(self, alarm_id: int) -> dict: ...
    def ack_all_alarms(self) -> dict: ...
    def get_alarm_history(
        self, start: datetime, end: datetime, controller_id: int | None = ...,
    ) -> list[dict]: ...

    # Export
    def create_export(
        self, controller_id: int, start: str, end: str, fmt: str = ...,
    ) -> dict: ...
    def get_export_status(self, export_id: str) -> dict: ...
    def download_export(self, export_id: str, dest_path: Path) -> Path: ...

    # Stats
    def get_controller_stats(self, controller_id: int) -> dict: ...
    def get_all_stats(self) -> list[dict]: ...

    # User management
    def list_users(self) -> list[UserResponse]: ...
    def create_user(
        self, username: str, password: str, role: str,
    ) -> UserResponse: ...
    def update_user(
        self, user_id: int, role: str | None = ...,
        password: str | None = ..., active: bool | None = ...,
    ) -> UserResponse: ...
    def deactivate_user(self, user_id: int) -> UserResponse: ...

    # Project management
    def get_current_project(self) -> dict: ...
    def new_project(self, name: str, path: str) -> dict: ...
    def open_project(self, path: str) -> dict: ...
    def save_as_project(self, path: str) -> dict: ...

    # Lifecycle
    def close(self) -> None: ...
