"""Inbound port interfaces — data flows into the domain."""
from __future__ import annotations

from typing import TYPE_CHECKING, Protocol

if TYPE_CHECKING:
    from smart_pid_domain.models.telemetry import TelemetryFrame

class TelemetrySource(Protocol):
    def read_telemetry(self, controller_id: int) -> TelemetryFrame: ...
    def start(self) -> None: ...
    def stop(self) -> None: ...

class TagBrowser(Protocol):
    def browse_children(self, node_id: str) -> list[dict[str, str]]: ...
    def search(self, query: str) -> list[dict[str, str]]: ...
