/**
 * Per-theme token VALUE MIRROR for the build-time contrast gate. Mirrors
 * themes.css exactly (sync-tested there); guard-exempt (token-guard EXCLUDE_FILES).
 * Field → token: camelCase of the §6.4 name (surfaceSunk → --surface-sunk, …).
 */
export type GateThemeId = 'optimizer' | 'optimizer-dark' | 'recorder' | 'phosphor' | 'neon';

export interface ThemePalette {
  bg: string;
  surface: string;
  surfaceSunk: string;
  ruleStrong: string;
  text: string;
  textSoft: string;
  focusRing: string;
  selection: string;
  accent: string;
  accentHover: string;
  onAccent: string;
  alarmCrit: string;
  alarmCritBg: string;
  alarmWarn: string;
  alarmWarnBg: string;
  alarmAdv: string;
  alarmAdvBg: string;
  alarmLog: string;
  onAlarm: string;
  stateRunning: string;
  stateStopped: string;
  stateError: string;
  tracePv: string;
  traceSp: string;
  traceCo: string;
  trendBg: string;
  barTrack: string;
  barFill: string;
  barMarker: string;
}

export const PALETTES: Record<GateThemeId, ThemePalette> = {
  optimizer: {
    bg: '#F0F4F7',
    surface: '#FFFFFF',
    surfaceSunk: '#F0F4F7',
    ruleStrong: '#7A8B99',
    text: '#3F3F3F',
    textSoft: '#5C5C5C',
    focusRing: '#2B6BAE',
    selection: '#D5E3F2',
    accent: '#2B6BAE',
    accentHover: '#21578F',
    onAccent: '#FFFFFF',
    alarmCrit: '#C53030',
    alarmCritBg: '#F8DEDE',
    alarmWarn: '#8A691A',
    alarmWarnBg: '#F5E9D2',
    alarmAdv: '#4A148C',
    alarmAdvBg: '#ECE2F5',
    alarmLog: '#5A6B7A',
    onAlarm: '#FFFFFF',
    stateRunning: '#2F7D4F',
    stateStopped: '#5A6B7A',
    stateError: '#C53030',
    tracePv: '#2B6BAE',
    traceSp: '#7C8189',
    traceCo: '#3F3F3F',
    trendBg: '#F0F4F7',
    barTrack: '#F0F4F7',
    barFill: '#2B6BAE',
    barMarker: '#3F3F3F',
  },
  'optimizer-dark': {
    bg: '#060D1A',
    surface: '#142944',
    surfaceSunk: '#0A1526',
    ruleStrong: '#5E7997',
    text: '#FFFFFF',
    textSoft: '#B8C2CE',
    focusRing: '#FF8C42',
    selection: '#1B3A63',
    accent: '#FF8C42',
    accentHover: '#FFB380',
    onAccent: '#0D1F38',
    alarmCrit: '#FF6B6B',
    alarmCritBg: '#3A0E0E',
    alarmWarn: '#FFB020',
    alarmWarnBg: '#3A2600',
    alarmAdv: '#C08CFF',
    alarmAdvBg: '#241A3E',
    alarmLog: '#B8C2CE',
    onAlarm: '#0D1F38',
    stateRunning: '#4ED88B',
    stateStopped: '#8DA0B5',
    stateError: '#FF6B6B',
    tracePv: '#6FB4F0',
    traceSp: '#9AA7B4',
    traceCo: '#FFB380',
    trendBg: '#0A1526',
    barTrack: '#0A1526',
    barFill: '#6FB4F0',
    barMarker: '#FFFFFF',
  },
  recorder: {
    bg: '#F7F8FA',
    surface: '#FFFFFF',
    surfaceSunk: '#EEF1F5',
    ruleStrong: '#7C8894',
    text: '#16202B',
    textSoft: '#5A6875',
    focusRing: '#16202B',
    selection: '#DCEBEB',
    accent: '#0E6B6B',
    accentHover: '#0B5757',
    onAccent: '#FFFFFF',
    alarmCrit: '#C02026',
    alarmCritBg: '#F7DCDC',
    alarmWarn: '#9E5E00',
    alarmWarnBg: '#F5E3CC',
    alarmAdv: '#6B4FA8',
    alarmAdvBg: '#E8E1F4',
    alarmLog: '#5A6875',
    onAlarm: '#FFFFFF',
    stateRunning: '#7C8894',
    stateStopped: '#5A6875',
    stateError: '#C02026',
    tracePv: '#1B4F87',
    traceSp: '#7C8894',
    traceCo: '#BC7211',
    trendBg: '#EEF1F5',
    barTrack: '#EEF1F5',
    barFill: '#5A6875',
    barMarker: '#16202B',
  },
  phosphor: {
    bg: '#0A0E14',
    surface: '#131A24',
    surfaceSunk: '#0E141C',
    ruleStrong: '#54697F',
    text: '#D6DEE8',
    textSoft: '#8894A3',
    focusRing: '#D6DEE8',
    selection: '#16304A',
    accent: '#23A6A6',
    accentHover: '#2FBDBD',
    onAccent: '#0A0E14',
    alarmCrit: '#FF4D4D',
    alarmCritBg: '#3A0E0E',
    alarmWarn: '#FFA51F',
    alarmWarnBg: '#3A2A00',
    alarmAdv: '#A98BFF',
    alarmAdvBg: '#241A3E',
    alarmLog: '#8894A3',
    onAlarm: '#0A0E14',
    stateRunning: '#5E7080',
    stateStopped: '#8894A3',
    stateError: '#FF4D4D',
    tracePv: '#9FC8F0',
    traceSp: '#6E7B8A',
    traceCo: '#E39B3D',
    trendBg: '#0A0E14',
    barTrack: '#0E141C',
    barFill: '#5E7080',
    barMarker: '#8FB6D6',
  },
  neon: {
    bg: '#07070E',
    surface: '#101226',
    surfaceSunk: '#0A0B18',
    ruleStrong: '#5A60A8',
    text: '#E9ECFF',
    textSoft: '#A6ADDC',
    focusRing: '#00E5FF',
    selection: '#1B2A5C',
    accent: '#00E5FF',
    accentHover: '#66F2FF',
    onAccent: '#04040A',
    alarmCrit: '#FF2D6F',
    alarmCritBg: '#3A0A1C',
    alarmWarn: '#FFB020',
    alarmWarnBg: '#3A2600',
    alarmAdv: '#C77DFF',
    alarmAdvBg: '#28123E',
    alarmLog: '#A6ADDC',
    onAlarm: '#04040A',
    stateRunning: '#39FF88',
    stateStopped: '#A6ADDC',
    stateError: '#FF2D6F',
    tracePv: '#00F0FF',
    traceSp: '#B8BEE8',
    traceCo: '#FFA630',
    trendBg: '#07070E',
    barTrack: '#12142A',
    barFill: '#00E5FF',
    barMarker: '#FFFFFF',
  },
};